<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fstojilj.luddite</groupId>
        <artifactId>luddite-sync-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>server-sync</artifactId>
    <name>Server Sync</name>
    <description>Leader node - serves photos and handles sync requests</description>
    <dependencies>
        <!-- Common module -->
        <dependency>
            <groupId>com.fstojilj.luddite</groupId>
            <artifactId>common-sync</artifactId>
        </dependency>
        <!-- Spring JDBC -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <jvmArguments>-Djava.net.preferIPv4Stack=true</jvmArguments>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
