spring:
  application:
    name: server-sync
  datasource:
    url: jdbc:sqlite:${user.home}/.luddite/server/photos.db
    driver-class-name: org.sqlite.JDBC
  jdbc:
    template:
      query-timeout: 5

server:
  port: 8080

sync:
  socket:
    port: 8888
    keystore: classpath:server-keystore.p12
    truststore: classpath:truststore.p12
    password: ${KEYSTORE_PASSWORD}
    pending-ack-ttl-ms: 20000
    tls-enabled: true

