spring:
  application:
    name: client-sync
  datasource:
    url: jdbc:sqlite:${user.home}/.luddite/client/sync.db
    driver-class-name: org.sqlite.JDBC
  jdbc:
    template:
      query-timeout: 5

sync:
  server:
    host: localhost
    port: 8888
    api-url: http://${sync.server.host}:8080
  client:
    mirror-dir: ${user.home}/.luddite
    retain-local-directory: true
    ui: swing
    name: xyz-client
  socket:
    keystore: classpath:client-keystore.p12
    truststore: classpath:truststore.p12
    password: ${KEYSTORE_PASSWORD}

