spring:
  application:
    name: client-sync
  datasource:
    url: jdbc:sqlite:${user.home}/.luddite/client/sync.db
    driver-class-name: org.sqlite.JDBC
  jdbc:
    template:
      query-timeout: 5

sync:
  server:
    api-port: 8080
  client:
    mirror-dir: ${user.home}/.luddite
    retain-local-directory: true
    ui: swing
    name: luddite-client
